spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3307/easytour?createDatabaseIfNotExist=true
    username: root
    password:
  devtools:
    restart:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: khai.nguyenanh03@gmail.com
    password: kzjc ypor dlmd tjgh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    jpa:
      repositories:
        base-package: com.easy.tour.repository